name: Build & Deploy Resume

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Cache Puppeteer Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            puppeteer-${{ runner.os }}-

      - name: Install deps
        run: npm ci

      - name: Generate PDF
        run: node resume-to-pdf.js
        env:
          GITHUB_SHA: ${{ github.sha }}

      # Option A: copy whatever PDF was produced into /public and add a cache-busted copy
      - name: Collect PDF into public (robust)
        run: |
          set -euo pipefail
          mkdir -p public

          echo "Looking for PDFs in repo root..."
          ls -lah || true

          PDF_SRC="Divyansh_Rana_Resume.pdf"
          if [ ! -f "$PDF_SRC" ]; then
            echo "Expected $PDF_SRC not found. Searching for any *.pdf..."
            PDF_SRC=$(ls -1 *.pdf 2>/dev/null | head -n1 || true)
          fi

          if [ -z "${PDF_SRC:-}" ] || [ ! -f "$PDF_SRC" ]; then
            echo "ERROR: No PDF found in repo root after generation."
            exit 1
          fi

          echo "Found PDF: $PDF_SRC"
          cp "$PDF_SRC" public/Divyansh_Rana_Resume.pdf
          cp public/Divyansh_Rana_Resume.pdf "public/Divyansh_Rana_Resume_${GITHUB_SHA}.pdf"

          echo "Listing public/ after copy:"
          ls -lah public
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Verify PDF exists and print checksums
        run: |
          set -euo pipefail
          test -f public/Divyansh_Rana_Resume.pdf || (echo "PDF not in public/"; exit 1)
          echo "SHA256 (stable):"
          sha256sum public/Divyansh_Rana_Resume.pdf
          echo "SHA256 (versioned):"
          sha256sum "public/Divyansh_Rana_Resume_${GITHUB_SHA}.pdf"
        env:
          GITHUB_SHA: ${{ github.sha }}

      # Auto-generate a tiny landing page with stable + fresh links
      - name: Generate index.html with links
        run: |
          COMMIT=${GITHUB_SHA}
          DATE_ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          mkdir -p public
          cat > public/index.html <<'HTML'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Divyansh Rana — Resume</title>
            <style>
              :root { --fg:#0f172a; --muted:#475569; --bg:#f8fafc; --card:#ffffff; }
              *{box-sizing:border-box}
              body { margin:0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; color:var(--fg); background:var(--bg); }
              .wrap { max-width: 880px; margin: 48px auto; padding: 24px; }
              .card { background:var(--card); border-radius:16px; padding:24px; box-shadow:0 6px 24px rgba(2,6,23,.06); }
              h1 { margin:0 0 8px; font-size:28px; }
              .meta { color:var(--muted); margin-bottom:16px; font-size:14px; }
              .links a { display:inline-block; margin-right:16px; padding:10px 14px; border-radius:10px; text-decoration:none; border:1px solid #e2e8f0; }
              .links a:hover { background:#f1f5f9; }
              code { background:#f1f5f9; padding:2px 6px; border-radius:6px; }
            </style>
          </head>
          <body>
            <div class="wrap">
              <div class="card">
                <h1>Divyansh Rana — Resume</h1>
                <div class="meta">
                  Built at <span id="built"></span>,
                  commit <code id="sha-short"></code>
                </div>
                <div class="links">
                  <a href="Divyansh_Rana_Resume.pdf">Stable PDF</a>
                  <a id="fresh" href="#">Fresh (per-commit) PDF</a>
                </div>
              </div>
            </div>
            <script>
              (function() {
                var sha = "{{SHA}}";
                var iso = "{{DATE_ISO}}";
                document.getElementById('fresh').href = 'Divyansh_Rana_Resume_' + sha + '.pdf';
                document.getElementById('sha-short').textContent = sha.slice(0,7);
                document.getElementById('built').textContent = new Date(iso).toUTCString();
              })();
            </script>
          </body>
          </html>
          HTML
          sed -i "s/{{SHA}}/${COMMIT}/g" public/index.html
          sed -i "s/{{DATE_ISO}}/${DATE_ISO}/g" public/index.html
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4