name: Build and Deploy Resume

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.actor != 'github-actions[bot]'  # skip if commit was made by the bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false # prevents token conflicts

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Cache Puppeteer Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            puppeteer-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Generate PDF
        run: node resume-to-pdf.js

      - name: Commit PDF back to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Divyansh_Rana_Resume.pdf
          git commit -m "chore: update generated resume PDF [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    if: github.actor != 'github-actions[bot]'  # also skip deploy loop
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # deploy everything (HTML + PDF)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4