name: Build and Deploy Resume

on:
  push:
    branches:
      - main  # run on every push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22  # or your version

      - name: Install dependencies
        run: npm install

      - name: Generate PDF
        run: node resume-to-pdf.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: Divyansh_Rana_Resume.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # deploy everything (HTML + PDF)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4